### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by manuelpapa** [manuelpapa/food-sharing-app#34]
# User story

As a **developer**,
I want to **declare my MVP.**

# Notes / Links
Clickdummy:
https://xd.adobe.com/view/c1ea0038-58f3-45c8-90d5-8690a58708da-94b9/

# Acceptance criteria

## Core features
- [x] Login screen: Possibility to login via e-mail and password
- [x] List screen: Fetch all active offers from database and display them in a list
- [x] List detail screen: after clicking/tapping on item:
  1. [x] Information about the offer
  2. [x] Reservation functionality 
- [x] User area: Display user's offers, reservations and their status
- [x] Create offer: Provide the functionality to add an item to the list

## Optional features
- [ ] Sort-by and filter functionality for the list screen
- [ ] Option to delete or modify an offer
- [ ] Option to cancel a reservation
- [ ] Settings
- [ ] anything else
